name: Build Desktop App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_FOR_WINDOWS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Assurez-vous que cette version est disponible

    - name: Install MAUI workload for Windows
      run: dotnet workload install maui-windows

    - name: Restore NuGet packages
      run: dotnet restore Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj /p:BUILD_FOR_WINDOWS=true

    - name: Build the project
      run: dotnet build Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj --configuration Release /p:UseMaui=true /p:BUILD_FOR_WINDOWS=true

    - name: Create App Packages
      run: dotnet publish Dtwo.App.DesktopApp/Dtwo.App.DesktopApp.csproj --configuration Release --framework net8.0-windows10.0.22621.0 /p:BUILD_FOR_WINDOWS=true -o ./publish

    - name: Copy Data folder
      run: |
        Copy-Item -Path ./Data -Destination ./publish/Data -Recurse
 
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./publish
